services:
  users.mongo:
    image: mongo
    container_name: users.mongo

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: users

    ports:
      - 27017:27017

    volumes:
      - ./db:/data/db

    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/users --quiet
      interval: 10s
      timeout: 10s
      retries: 5

  user.mongo.ui:
    image: mongo-express
    container_name: user.mongo.ui
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:pass@users.mongo:27017/
