
version: '3.5'
services:
  blog.postgres:
    image: postgres:14-alpine
    container_name: blog.postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: blog
    ports:
      - 5432:5432
    volumes:
      - ./db:/var/lib/postgresql/data

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d pass" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - typoteka.blog

  blog.pgadmin:
    image: dpage/pgadmin4
    container_name: blog.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "test@mail.local"
      PGADMIN_DEFAULT_PASSWORD: "pass"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - 8082:80
    networks:
      - typoteka.blog


networks:
  typoteka.blog:
      driver: bridge